#!/usr/bin/env bash
# write a Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument
# Check if an argument is provided
if [ -z "$1" ]; then
  echo "Please provide a user as an argument."
  exit 1
fi

# Run the 'whoami' command under the specified user
sudo -u "$1" whoami
